### PR TITLE
CUMULUS-321: Cumulus Message Adapter unit tests

### PR DESCRIPTION
**Pull request by jennyhliu**
Add unittests for the cumulus-message-adapter command-line interface.
Also fix pylint warnings in the test-module.py.

### CODE REVIEW

**Comment by matthewhanson** [comment]
First issue I have run into here is an error creating a bucket since there are too many buckets. 

IMO the tests should not actually create buckets, calls to boto3 should be mocked. Mocking individual functions in boto3 can be tricky, you have to use the botocore stub functionality, or what I did in cumulus-process-py is just patch the entire boto3 module which worked there because I wasn't relying on a return value. I think it might be the same case here.

Also, for mocking in python2 and 3, you have to do the import a little different since mock is part of the python3 unittest (the mock library for python2.7 is a backport of this lib)

```
try:
    from mock import patch
except ImportError:
    from unittest.mock import patch
```

See how I mock boto in cumulus-process-py here
https://github.com/cumulus-nasa/cumulus-process-py/blob/develop/test/test_s3.py

@jennyhliu @sethvincent @laurenfrederick

**Comment by jennyhliu** [comment]
@matthewhanson Could you review Seth's pull request?  He has some updates for working with python 3.
https://github.com/cumulus-nasa/cumulus-message-adapter/pull/29

**Comment by sethvincent** [comment]
The PR for ci updates has a fix for the unicode problem. We should probably merge that one first, then update this branch.

Also I think the plan was to run tests against localstack rather than use mocks.

**Comment by matthewhanson** [comment]
Ah yes, I see that @sethvincent made the required changes for unicode and python3 @jennyhliu , cool

**Comment by matthewhanson** [comment]
ah right, yes localstack is a better solution that mocks @sethvincent , also cool

**Comment by jennyhliu** [comment]
@sethvincent I made updates, and tested the program under python 27 and 36 by using pyenv.  Thanks!

**Pull request merged**
