### PR TITLE
cumulus-309 update circle ci

### PR DESCRIPTION
**Pull request by sethvincent**
This branch should probably be squashed.

This PR:
- **sets the version to v1.0.0**, which will be published to github releases and pypi on merge
- makes small fixes that allow `__main__.py` and `message_adapter.py` to run in both python 2 & 3
- sets up circle ci to test the code in both python 2.7 and 3.6
- uses pylint to check for errors in `__main__.py`. this will help us catch build problems like we saw last week

You can see an example of workflows with passing builds here:
- python 2.7: https://circleci.com/workflow-run/8b4d19f7-735b-46aa-8b30-f0785c243a5c
- python 3.6: https://circleci.com/workflow-run/ff5f0fdc-99f0-43e5-ad30-65f0c7c6cdbd
  - this workflow includes the jobs for publishing to github and pypi

The pypi release from the above job is available to try out: https://pypi.org/project/cumulus-message-adapter/1.0.0a1/

### CODE REVIEW

**Comment by sethvincent** [comment]
I think circleci is confused. I removed the `build` job and replaced it with jobs for python 2.7 and 3.6, but it's still waiting for `build`. I think that can safely be ignored.

I plan to do a squash & merge with this PR to hide my silly commit messages.

**Comment by sethvincent** [comment]
Oh but github won't let me ignore the `build` job. @matthewhanson ideas on that? Or anything else that looks wonky?

**Comment by matthewhanson** [comment]
This looks good to me overall @sethvincent .  Concerning the addition of checking if the tag exists first before pushing the tag to github: So if the tag already exists on github then it won't push, and the publish to pypi will also be attempted and probably fail, because the version presumably exists.

But, in the case where the tag already exist on github but for some reason it does *not* exist on pypi then the tagged version between github and pypi could be different.   Not a likely scenario, but I could see it happening.

**Comment by sethvincent** [comment]
@matthewhanson cool, thanks. yeah I think it would be good to revisit the tag checking/creation part of the script.

**Comment by sethvincent** [comment]
This was closed as an experiment to see if the circle ci ghost build could be removed.

**Comment by sethvincent** [comment]
The plan now is to disable the status check requirement just for this PR so that it can be merged, then reenable status check requirements.

**Comment by sethvincent** [comment]
Just learned there's checkboxes to toggle on/off specific status checks 🎉

**Pull request merged**
